Add new crate for ics101 integration
sideprotocol/ibcswap-wasm pull request #6
Opened 2023-06-05 11:42 UTC by luckiester

Add new crate for ics101 integration

2023-06-06 02:45 UTC, liangping requested changes

2023-06-06 02:45 UTC, liangping commented on contracts/ics101/src/contract.rs
> +    let amm = InterchainMarketMaker {
pool and pool id are duplicated arguemnts

2023-06-06 02:45 UTC, liangping commented on contracts/ics101/src/contract.rs
> +    let pool = POOLS.load(deps.storage, &msg.pool_coin.denom)?;
Do we need check pool status here.

2023-06-06 02:45 UTC, liangping commented on contracts/ics101/src/contract.rs
> +    )?;
How to make sure that the sender has enough pool tokens on remote chain?

2023-06-06 02:45 UTC, liangping commented on contracts/ics101/src/contract.rs
> +    )?;
need to check if the sender have enough pool tokens

2023-06-06 02:45 UTC, liangping commented on contracts/ics101/src/contract.rs
> +    match msg.swap_type {
need check if the sender has deposited in tokens

2023-06-06 02:45 UTC, liangping commented on contracts/ics101/src/contract.rs
> +    match msg.swap_type {
and also need check deposit amount should equal msg.token_in

2023-06-06 02:45 UTC, liangping commented on contracts/ics101/src/market.rs
> +        } else {
we can remove this now. pool will become `ready` status once it's created.

2023-06-28 08:52 UTC, amityadav0 commented
Merged via different branch #9 #10

2023-06-28 08:52 UTC, closed without merging